apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      web: static-web
  template:
    metadata:
      labels:
        web: static-web
    spec:
      containers:
      - image: minhbui1/static-web
        name: static-web
        ports:
        - containerPort: 80