apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      web: web1
  template:
    metadata:
      labels:
        web: web1
    spec:
      containers:
      - image: minhbui1/web1
        name: web1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web1-service
  namespace: dev 
spec:
  type: NodePort
  selector:
    web: web1
  ports:
    - port: 80         
      targetPort: 80 
      nodePort: 30001
