apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      web: web2
  template:
    metadata:
      labels:
        web: web2
    spec:
      containers:
      - image: minhbui1/web2
        name: web2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web2-service
  namespace: dev 
spec:
  type: NodePort
  selector:
    web: web2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002